### ISSUE TITLE
[unit testing] update "tests:" to "data_tests"

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-jsonschema#104]
With the introduction of unit testing (coming to `dbt-core` in `1.8`), we are changing the prior `tests:` configs to `data_tests:` (though `tests:` with still be supported for backwards compatibility).  

- in schema yml update `tests:` to `data_tests:`
- in dbt_project.yml update `tests:` to `data_tests:`

**Comment by joellabes** [comment]
@graciegoheen I am working on this now! 

Some questions/comments: 
- If we're maintaining support for tests as well as data_tests, I don't think I want to do a rename so much as adding this as a second option. (This is easy to do)
- Is it legal to have both a tests and a data_tests block? 

```yaml
# dbt_project.yml

tests: 
  joel_sandbox:
    marts:
      +enabled: false

data_tests:
  joel_sandbox:
    marts:
      +enabled: true
```

I assume not, and you're only allowed one of those?

**Comment by graciegoheen** [comment]
I just tested this with:
```
version: 2

models:
  - name: dim_wizards
    columns:
      - name: wizard_id
        data_tests:
          - unique
          - not_null
  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
```

And that seems to have worked fine. When I ran `dbt build`, I get the warning:
```
[WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please update your
`dbt_project.yml` configuration to reflect this change.
```

Otherwise, everything runs as expected: 
<img width="921" alt="Screenshot 2024-01-18 at 12 20 46 PM" src="https://github.com/dbt-labs/dbt-jsonschema/assets/53586774/808d5024-f743-4524-9056-0339cf364cc5">
