### ISSUE TITLE
[unit testing] create new top level "unit_tests:"

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-jsonschema#106]
With the introduction of unit testing (coming to `dbt-core` in `1.8`), we should create a new top level `unit_tests:` schema yml block. 

Current spec as follows:
```
unit_tests:
  - name: <test-name> # this is the unique name of the test
    model: <model-name> 
    config: 
      meta: {dictionary}
      tags: <string> | [<string>]
    given:
      - input: <ref_or_source_call> # optional for seeds
        format: dict | csv
        # if format csv, either define dictionary of rows or name of fixture
        rows:
          - {dictionary}
        fixture: <fixture-name>
      - input: ... # declare additional inputs
    expect:
      format: dict | csv
      # if format csv, either define dictionary of rows or name of fixture
      rows: 
        - {dictionary}
      fixture: <fixture-name>
    overrides: # optional: configuration for the dbt execution environment
      macros:
        is_incremental: true | false
        dbt_utils.current_timestamp: str
	  # ... any other jinja function from https://docs.getdbt.com/reference/dbt-jinja-functions
          # ... any other context property
        vars: {dictionary}
        env_vars: {dictionary}
  - name: <test-name> ... # declare additional unit tests
```

More examples [here](https://www.notion.so/dbtlabs/Unit-Testing-Documentation-Changes-0d00d8077b044607878faecdd39831d3)
