### ISSUE TITLE
Support for grant_access_to

### ISSUE THREAD

**Issue by kieronellis** [dbt-labs/dbt-jsonschema#11]
https://docs.getdbt.com/reference/resource-configs/bigquery-configs#authorized-views
![image](https://user-images.githubusercontent.com/69465049/188182583-d7112ed8-f4f2-46ff-8ab1-f5bb2dfb8dfe.png)

e.g. this
```
models:
  on_running:
    +enabled: true
    +persist_docs:
      relation: true
      columns: true
    final:
      salesforce:
        +grant_access_to:
          - project: "{{ target.project }}"
            dataset: "{{ target.dataset }}_stg_sf"
```

currently results in everything from `-project: ` being underlined in red with the error `Incorrect type. Expected "Model configs".yaml-schema: Model configs`.
