### ISSUE TITLE
Support sql as a unit test `format` 

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-jsonschema#140]
<img width="616" alt="image" src="https://github.com/dbt-labs/dbt-jsonschema/assets/7335046/2ddde8b6-66a3-4d1f-95c0-09bfcc4ccdf7">

```
  - name: reworked_compare_struct
    model: unit_reworked_compare_struct
    given:
      - input: ref('unit_test_struct_model_a')
        format: sql
        rows: |
          select 1 as id, 'John Doe' as col1, object_construct('street', '123 Main St', 'city', 'Anytown', 'state', 'CA') as col2
      - input: ref('unit_test_struct_model_b')
        format: sql
        rows: |
          select 1 as id, 'John Doe' as col1, object_construct('street', '123 Main St', 'city', 'Anytown', 'state', 'CA') as col2
    expect:
      rows:
        - {"id": 1, "dbt_audit_row_status": "identical", "dbt_audit_num_rows_in_status": 1}
    overrides:
      vars:
        reworked_compare__columns: ['id', 'col1', 'col2']
        reworked_compare__event_time:
        reworked_compare__primary_key_columns: ['id']
```

sql format has rows as a string, and also supports defining a fixture. Basically the same as csv
