### ISSUE TITLE
Snapshot YML is not supported

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-jsonschema#15]
Opening this snapshot YML format gives `Propery snapshots is not allowed`:

```
snapshots:
  - name: snapshot_name
    description: description_text
    columns:
...
```

I use snapshot YML to document field descriptions and snapshot integrity - think the same YML format as models should work with the snapshot key.
