### ISSUE TITLE
Meta field missing for models

### ISSUE THREAD

**Issue by stevenlw-porpoise** [dbt-labs/dbt-jsonschema#17]
The meta field is missing from model properties - as well as other resources I believe it is supported for ([docs](https://docs.getdbt.com/reference/resource-configs/meta)) such as seeds, tests, etc. 

As a result a yml file like
```
version: 2

models:
  - name: my_model
    description: stuff
    meta:
      tags:
        my_tag
    columns:
      - name: col1
        description: first column
      - name: col2
        description: second column
```
will highlight a problem on the meta field that `Property meta is not allowed. yaml-schema: dbt_yml_files`

I'm happy to add a PR for this as long as I my understanding is correct that this is valid dbt config and can be fixed by adding a "meta" key to the list of properties for each resource.
