### ISSUE TITLE
Add data_tests block as a top level dbt type so that you can document singular tests

### ISSUE THREAD

**Issue by joellabes** [dbt-labs/dbt-jsonschema#174]
https://docs.getdbt.com/docs/build/data-tests#singular-data-tests

```yml
# tests/singular_tests.yml
version: 2
data_tests:
  - name: assert_total_payment_amount_is_positive
    description: >
      Refunds have a negative amount, so the total amount should always be >= 0.
      Therefore return records where total amount < 0 to make the test fail.
```
