### ISSUE TITLE
Have `freshness_rules` optional for Tables

### ISSUE THREAD

**Issue by vicmattos** [dbt-labs/dbt-jsonschema#188]
# Scenario

I have a source wide freshness configuration (outside of `tables` key) with `warn_after` for 2 days and `error_after` for 3.

There's one table in this source definition that would like to configure to alert me only after 30 days, so I overwrite the source wide config only for that.

Since it's a big timeframe, would like to get an error without the warning.

```
version: 2

sources:
  - name: schema_name
    
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 3, period: day}

    tables:
      - name: table_name
        freshness:
          warn_after:
          error_after: {count: 30, period: day}
```

# Current State

The empty key `warn_after` returns the error `Incorrect type. Expected "freshness_rules".`

# Proposal

Make the `freshness_rules` optional for table freshness
