### ISSUE TITLE
`install-prerelease` (packages, dependencies) is not a valid property

### ISSUE THREAD

**Issue by pierrand** [dbt-labs/dbt-jsonschema#191]
Using the `install-prerelease` property in `packages.yml` and `dependencies.yml` results in a runtime error during `dbt deps` execution.

Example `packages.yml`:
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: ">=1.0.0"
    install-prerelease: true
```

Error message:
```
Runtime Error
  The packages.yml file in this project is malformed. Please double check
  the contents of this file and fix any errors before retrying.
 
  You can find more information on the syntax for this file here:
  https://docs.getdbt.com/docs/package-management
 
  Validator Error:
  {'package': 'dbt-labs/dbt_utils', 'version': '>=1.0.0', 'install-prerelease': True, 'unrendered': {...}} is not valid under any of the given schemas
```

According to the [documentation](https://docs.getdbt.com/docs/build/packages), the correct property name is `install_prerelease`
