### ISSUE TITLE
'quoting' property is not in schema for dbt_project.yml

### ISSUE THREAD

**Issue by joel-olazagasti** [dbt-labs/dbt-jsonschema#25]
Issue:
The following block of yaml config throws a yaml-schema error, but should be valid config per DBT docs [here](https://docs.getdbt.com/reference/dbt_project.yml)
```
quoting:
  database: false
  schema: false
  identifier: false
```
