### ISSUE TITLE
Make table-level and column-level `meta` extensible for other tools

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-jsonschema#68]
## Motivation
Some tools which integrate with dbt defines their own custom schema under the `meta` property at table-level and column-level.
For instance, lightdash enables us to declare metrics like below. 

https://docs.lightdash.com/guides/how-to-create-metrics

```yaml
# schema.yml
version: 2
models:
  - name: "orders"
    description: "A table of all orders."
    columns:
      - name: "status"
        description: "Status of an order: ordered/processed/complete"
      - name: "order_id"
        meta:
          metrics:
            total_order_count:
              type: count_distinct
      - name: "order_value"
        meta:
          metrics:
            total_sales:
              type: sum
```

I don't have any good ideas to support such extensibility in JSON schema. But, if we make the JSON schema opened to other tools, that would be awesome. 

https://github.com/dbt-labs/dbt-jsonschema/blob/main/schemas/dbt_yml_files.json#L680-L682
