### ISSUE TITLE
add metric `window`

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-jsonschema#69]
we missed a param! `window` is a dict that you can provide to metrics to do rolling calculations

```yml

metrics:
  - name: metric_name
     ...
     window:
       count: 14
       period: day
```
