### ISSUE TITLE
README Typo in JetBrains Selectors URL and Mapping

### ISSUE THREAD

**Issue by Bilbottom** [dbt-labs/dbt-jsonschema#72]
This is a teeny tiny issue -- [the `README.md` file](https://github.com/dbt-labs/dbt-jsonschema/blob/157d00c639b7522b9fb03f6f0f273a40b6ee0902/README.md) has used the singular "selector" rather than the plural "selectors" in the URL and mapping bullets:

https://github.com/dbt-labs/dbt-jsonschema/blob/157d00c639b7522b9fb03f6f0f273a40b6ee0902/README.md?plain=1#L100-L102

This should read as:
```yaml
 - URL: `https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/selectors.json` 
 - Schema version: JSON schema version 7 
 - Mapping: `selectors.yml`
```

Just for completeness, here's the docs page for the selectors which uses the plural name, and the link for the JSON schema validator (again to show the plural name):
* https://docs.getdbt.com/reference/node-selection/yaml-selectors
* https://github.com/dbt-labs/dbt-jsonschema/blob/main/schemas/selectors.json
