### ISSUE TITLE
Add support for `projects` in `dependencies.yml`

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-jsonschema#81]
```yml
# dependencies.yml

projects:
  - name: ...

packages:
  - ...
```

https://github.com/dbt-labs/docs.getdbt.com/pull/3577
